### ISSUE TITLE
GitHub Plugin to keep track of the code-quality in pull requests

### ISSUE THREAD

**Issue by Sander3003** [OSGP/Integration-Tests#11]
Hey Guys, 

Maybe we can use this plug-in to keep track of the code-quality in pull requests?
http://docs.sonarqube.org/display/PLUG/GitHub+Plugin

Let me know what you think.

**Comment by kevinsmeets** [comment]
Hi Sander,

We already saw this plugin and are planning to add it to our workflow.
Next sprint we will try to install the plugin and set it up.
Only potential problem is that the authors of the plugin have documented how to use it together with Travis CI. It is unclear if there's any information on Jenkins.

See this issue as wel: SSS/146

**Comment by Sander3003** [comment]
Hi Kevin, Thanks for the information, since this affects all developers, you can publish this idea in the open source community. Others (outside SSS) can join the discussion too.

**Comment by Sander3003** [comment]
Consider contacting/contracting the plug-in author to make it work with Jenkins.
